name: Build and Run Knomp with Docker and Redis

on:
  push:
    branches:
      - master  # or another branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the platform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2  # Set up Docker

    - name: Build and start Docker containers
      run: |
        # Clone the project and go into the knomp directory
        git clone https://github.com/TESTERT-TEST/knomps.git
        cd knomps

        # Copy the example config file
        cp config_example.json config.json

        # Run the Redis container
        docker run --name redis -d -p 6379:6379 redis:latest

        # Start the Knomp containers
        docker-compose up -d

        # Wait a few seconds for containers to initialize
        sleep 10

        # Get logs from the containers
        docker logs $(docker ps -q) > docker_logs.txt  # Save logs from all containers to a file
        cat docker_logs.txt  # Display the logs in the GitHub Actions console

    - name: Upload logs
      uses: actions/upload-artifact@v4  # Use the latest version (v3) of the upload-artifact action
      with:
        name: docker-logs
        path: docker_logs.txt  # Upload the logs file as an artifact
